---
#
# Install/Configure collectd
#

- name: Check for epel
  shell: rpm -qa | grep -q epel-release
  ignore_errors: true
  register: epel_installed

- name: Install epel repo (rhel7)
  command: rpm -ivh {{ epel7_rpm }}
  when: (epel_installed.rc != 0) and (is55 or is56)

- name: Install epel repo (rhel6)
  command: rpm -ivh {{ epel6_rpm }}
  when: (epel_installed.rc != 0) and is54

- name: Install collectd rpms (rhel7)
  yum: name={{ item }} state=present
  with_items: "{{collectd_packages[config_type]}}"
  when: (is55 or is56)

- name: Install collectd rpms (rhel6)
  yum: name={{ item }} state=present
  with_items:
    - "{{el6_collectd}}"
    - "{{el6_collectd_apache}}"
    - "{{el6_collectd_disk}}"
    - "{{el6_collectd_postgres}}"
  when: is54

- name: Copy cfme-http.conf for apache monitoring
  copy:
    src=cfme-http.conf
    dest=/etc/httpd/conf.d/cfme-http.conf
    owner=root
    group=root
    mode=0644
  when: cfme_apache_monitoring
  notify:
    - restart httpd

- name: Configure collectd.conf
  template:
    src={{config_type}}.collectd.conf.j2
    dest=/etc/collectd.conf
    owner=root
    group=root
    mode=0644

- name: Set SELinux Boolean collectd_tcp_network_connect
  seboolean: name=collectd_tcp_network_connect state=yes persistent=yes

- name: Set permissive for collectd
  shell: semanage permissive -a collectd_t

- name: Copy CFME collectd type enforcement file
  copy:
    src=cfme.te
    dest=/root/cfme.te
    owner=root
    group=root
    mode=644

- name: Convert cfme.te to cfme.mod
  command: checkmodule -M -m -o /root/cfme.mod /root/cfme.te

- name: Convert package cfme.mod to cfme.pp
  command: semodule_package -o /root/cfme.pp -m /root/cfme.mod

- name: Install SELinux policy for collectd
  command: semodule -i /root/cfme.pp

- name: Setup collectd service
  service: name=collectd state=restarted enabled=true

- name: Disable EPEL
  shell: rpm -e epel-release
  ignore_errors: true
