---
#
# Install/Configure collectd on the monitorhost
#

- name: Check for epel
  shell: rpm -qa | grep -q epel-release
  ignore_errors: true
  register: epel_installed

- name: Install epel repo
  command: rpm -ivh {{ epel7_rpm }}
  when: epel_installed.rc != 0

- name: Install collectd rpms
  yum: name={{ item }} state=present
  with_items:
    - collectd
    - collectd-turbostat
    - libsemanage-python
    - policycoreutils-python

- name: Configure collectd.conf
  template:
    src=monitorhost.collectd.conf.j2
    dest=/etc/collectd.conf
    owner=root
    group=root
    mode=0644

- name: Set SELinux Boolean collectd_tcp_network_connect
  seboolean: name=collectd_tcp_network_connect state=yes persistent=yes

- name: Set permissive for collectd
  shell: semanage permissive -a collectd_t

- name: Setup collectd service
  service: name=collectd state=restarted enabled=true

- name: Disable EPEL
  shell: rpm -e epel-release
  ignore_errors: true
